### ISSUE TITLE
:bd closes vim, even if other buffers exists

### ISSUE THREAD

**Issue by oryband** [weynhamz/vim-plugin-minibufexpl#11]
Open two buffers, then `:bd` on the second one. Vim will close.
I removed `minibufexpl` and the problem vanished.

Any idea how to fix this?

Thanks.

**Comment by weynhamz** [comment]
This is indeed a problem, will look into it.

**Comment by oryband** [comment]
Hi @techlivezheng. Any news on this?

**Comment by weynhamz** [comment]
@oryband, do not get time to dig into this recently, I will keep you post.

**Comment by oryband** [comment]
I don't mind getting into this myself, if you give me some lead or where to start looking in the code. Two are better than one, etc. :)

I'd really like to get this fixed, this pretty much makes the plugin useless.

**Comment by weynhamz** [comment]
@oryband hey, just work out a fix, might have a chance to break other quiting related functionality but it should fix this issue, would you give it a try, and let me know if there is any side-effect? It's on feature/quit-if-MBE-is-last branch.

By the way, the related functionality is in 'function! <SID>QuitIfLastOpen()' function, you might want to give it a shot yourself.

Thanks.

**Comment by oryband** [comment]
@techlivezheng I tested it, and Vim doesn't close, but once you `:bd`, the MiniBufferExplorer window closes and requires to be re-opened manually.

Try opening 3 buffers, and then `:bd` one of them. The two remaining buffers will still be open, but the MiniBufExplorer window will be closed.

**Comment by weynhamz** [comment]
Hey, @oryband, I have worked it out, but it requires the version of Vim is greater than 7.3.544, please fetch the lastest feature/quit-if-MBE-is-last branch, and give it a try.

Please do not use `git pull` directly, you might have confilict, do a `git fetch` and `git reset` will be fine.

**Comment by oryband** [comment]
I'm sorry, but this still isn't fixed.

MBE indeed doesn't close itself anymore, but something else popped up:

For me MBE opens at the bottom of the screen, but after `:bd` it moves to the top. I looked in `:help` but couldn't found any option to force it to the bottom manually.

Please re-open.

**Comment by weynhamz** [comment]
@oryband, yeah, right, it was introduced in this fix, will correct later. I usually open it at the top, so, sorry for that.

**Comment by weynhamz** [comment]
@oryband Just pushed a fix, please try the latest feature/quit-if-MBE-is-last branch.

**Comment by weynhamz** [comment]
It should be fixed now, closed.

**Comment by ericlathrop** [comment]
Thanks for working on minibufexpl, I really value this plugin!

This is can still be replicated with these commands:

```
vim Gemfile
:e Guardfile
:bd
```

I'm running ad72976ca3df4585d49aa296799f14f3b34cf953 in VIM 7.3 on Ubuntu Precise.
